export const GET_GALLERY_CONTENT = 'GET_GALLERY_CONTENT';
export const SET_SECTION = 'SET_SECTION';
export const SET_VIRAL_IMAGE_VISIBLITY = 'SET_VIRAL_IMAGE_VISIBLITY';
export const SET_WINDOW = 'SET_WINDOW';
export const SET_SORT = 'SET_SORT';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const CLEAR_POST = 'CLEAR_POST';